services:
  madr_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jean
      POSTGRES_DB: madr_db
      POSTGRES_PASSWORD: JC123
    ports:
      - "5432:5432"

  alembic:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - madr_database
    environment:
      DB_HOST: madr_database
      DB_PORT: 5432
      DB_NAME: madr_db
      DB_USER: jean
      DB_PASSWORD: JC123
    command: poetry run alembic upgrade head

volumes:
  pgdata:
